// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Accaunts, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Accaunts, error)
	CreateEnteries(ctx context.Context, arg CreateEnteriesParams) (Enteries, error)
	CreateTransfers(ctx context.Context, arg CreateTransfersParams) (Transfers, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Accaunts, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Accaunts, error)
	GetEnteries(ctx context.Context, id int64) (Enteries, error)
	GetTransfers(ctx context.Context, id int64) (Transfers, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Accaunts, error)
	ListEnteriess(ctx context.Context, arg ListEnteriessParams) ([]Enteries, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfers, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Accaunts, error)
}

var _ Querier = (*Queries)(nil)
